### ISSUE TITLE
Can't ignore ".venv/"

### ISSUE THREAD

**Issue by KPLauritzen** [olzhasar/pytest-watcher#20]
Just discovered this tool, looks very cool! Thanks for developing it!

I'm running `ptw .` and I want to ignore any changes in my virtualenv (installed at `.venv/` in the project root). 
I've tried
- `ptw . --ignore_patterns ".venv/"
- `ptw . --ignore_patterns ".venv/*"
- `ptw . --ignore_patterns ".venv*"

but none of them work. 

I think I have identified the issue. In `watcher.py` in `_is_event_watched` there is call to `match_any_paths`.
In `match_any_paths`, `case_sensitive` is an optional keyword, but it defaults to True. I'm on a Windows machine, so all my paths are being converted to a `PurePosixPath`.

**Comment by olzhasar** [comment]
@KPLauritzen,
Thank you for reporting this and opening the PR!

I currently do not have a Windows machine to test proposed changes. I will find time a bit later to test it and get back.

**Comment by lcnittl** [comment]
@KPLauritzen I am not sure case sensitivity is the root cause: If your venv dir is called `.venv` (lower case) then it should match on Windows if searched for `.venv\*` (lower case)

Have you tried prefixing your path with `.\`?

`ptw` reports changed paths and for me these do start with `.\` on Windows (e,g,: `.\.venv\...`. Prefixing solved the problem in my case.

**Comment by olzhasar** [comment]
I am closing this issue for now, because introducing case insensitive approach can lead to other problems as was mentioned in the [PR](https://github.com/olzhasar/pytest-watcher/pull/22)

@KPLauritzen Feel free to reopen if you will find more information about your case
