### ISSUE TITLE
`ptw` should call ptw on current directory 

### ISSUE THREAD

**Issue by thomasaarholt** [olzhasar/pytest-watcher#5]
Hi! Thanks for forking ptw and continuing it!
Since you've released pytest–watcher on pypi, automatic workflows are now picking your package over the old one, which is mostly great. Unfortunately, ptw could previously be run on the present working directory by calling `ptw` without options. The new version breaks this backward compatibility.
Unless you have very good reason to do, I suggest you re-introduce this behaviour.

**Comment by olzhasar** [comment]
@thomasaarholt Hi!
`pytest-watcher` is an independent project. It wasn't forked from any other repository, but written from scratch by me.
I'm not sure how exactly another package was working, but the reason `pytest-watcher` works like this is that it passes all subsequent arguments after the first one to `pytest` itself. I did not introduce any additional flags in order to avoid name conflicts with pytest. When calling `pytest`, you can also specify path from where tests should be ran. If I make the first argument optional, it will be cumbersome to differentiate between ptw's and pytest's path parameters.
